{% set name = "NeuroKit2" %}
{% set pypi_name = "neurokit2" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 0c33b060f9ac5ec8a6a0e23261fdbc36a98cb48e06142a1653fd12698806a952

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
    - numpy
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - matplotlib-base

test:
  imports:
    - neurokit2

about:
  home: https://neurokit2.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Python Toolbox for Neurophysiological Signal Processing
  description: |
    This package is the continuation of NeuroKit 1. It's a user-friendly
    package providing easy access to advanced biosignal processing routines.
    Researchers and clinicians without extensive knowledge of programming or
    biomedical signal processing can analyze physiological data with only two
    lines of code.
  dev_url: https://github.com/neuropsychology/NeuroKit

extra:
  recipe-maintainers:
    - hoechenberger
    - JanCBrammer
