{% set name = "NeuroKit2" %}
{% set pypi_name = "neurokit2" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 31e4eb2a187aa0c8eb26a63d0ef9072891d6b6d4dde384d9691b82074d539aba

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - numpy
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - matplotlib-base
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - neurokit2

about:
  home: https://neurokit2.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Python Toolbox for Neurophysiological Signal Processing
  description: |
    This package is the continuation of NeuroKit 1. It's a user-friendly
    package providing easy access to advanced biosignal processing routines.
    Researchers and clinicians without extensive knowledge of programming or
    biomedical signal processing can analyze physiological data with only two
    lines of code.
  dev_url: https://github.com/neuropsychology/NeuroKit

extra:
  recipe-maintainers:
    - hoechenberger
    - JanCBrammer
